### ISSUE TITLE
domain / website does not exist anymore

### ISSUE THREAD

**Issue by DanielRuf** [emeralt/emeralt#166]
Hi, emeralt.org does not seem to exist anymore.

https://emeralt.org

![Bildschirmfoto 2019-05-13 um 11 50 52](https://user-images.githubusercontent.com/827205/57612572-62292d80-7575-11e9-952a-0769675b6679.png)

**Comment by stackdumper** [comment]
Hello, this project is archived in favor of [`npm-package-registry`](https://github.com/pkgems/npm-package-registry).
